# Generated by Django 3.1 on 2022-10-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('images', models.ManyToManyField(blank=True, to='marchant.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], default='R', max_length=1)),
                ('timeframe', models.CharField(choices=[('L', 'Lifetime'), ('M', 'Monthly'), ('Y', 'Yearly')], default='Y', max_length=1)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('images', models.ManyToManyField(blank=True, to='marchant.Images')),
                ('sub_product', models.ManyToManyField(blank=True, to='marchant.Sub_Product')),
            ],
        ),
    ]
