# Generated by Django 3.1 on 2022-10-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate1', models.IntegerField()),
                ('rate2', models.IntegerField()),
                ('rate3', models.IntegerField()),
                ('rate4', models.IntegerField()),
                ('rate5', models.IntegerField()),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marchant.product')),
            ],
        ),
    ]
