# Generated by Django 3.1 on 2022-10-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0004_auto_20221012_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Product',
            new_name='SubProduct',
        ),
    ]
