# Generated by Django 3.1 on 2022-10-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0008_auto_20221013_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='body',
            field=models.TextField(max_length=150),
        ),
    ]
