# Generated by Django 3.1 on 2022-10-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0011_auto_20221014_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marchant.rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, null=True, to='marchant.Reviews'),
        ),
    ]
