# Generated by Django 3.1 on 2022-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0014_auto_20221014_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
