# Generated by Django 3.1 on 2022-10-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0017_auto_20221014_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marchant.product'),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
