# Generated by Django 3.1 on 2022-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], max_length=2)),
                ('value', models.BigIntegerField()),
            ],
        ),
    ]
