# Generated by Django 3.1 on 2022-10-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0005_auto_20221012_2013'),
        ('customer', '0003_auto_20221012_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='marchant.Product')),
            ],
        ),
    ]
