# Generated by Django 3.1 on 2022-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sell'), ('B', 'Sell & Rent'), ('C', 'Customer')], max_length=1),
        ),
    ]
